
maxt    : 48
abbrev  : abq
name    : Albuquerque (TEST)
gdb     : I:\\urbphen\\ws_done\\datasets\\abq.gdb
outpath : I:\\urbphen\\netcdf\\abqtest
yaml    : I:\\urbphen\\netcdf\\abqtest\\info.yaml
netcdf  : I:\\urbphen\\netcdf\\abqtest\\data.nc
climate_type: semiarid
climate_rank: 3

JoinCensus:
  tractshp : I:\\urbphen\\JoinedCensusTracts\\abq.shp
  extractfields:
    - FAVINC0
    - BLTBEF80
    - BLTAFT80

NLCD_Prep:
  file: I:\\urbphen\\NLCD2001\\save\\abq0
  outfile : I:\\urbphen\\NLCD2001\\abq1
  origvals: [11, 12, 21, 22, 23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]   
  newvals : [10, 10, 21, 21, 23, 23, 30, 40, 40, 40, 50, 50, 81, 82, 90, 90]
  thresh : 0.70

landcover:
  file: I:\\urbphen\\NLCD2001\\abq1
  name : NLCD
  dtype: i1
  units: land cover category
  description: Land cover aggregated from NLCD 2001

