maxt        : null
importmodis : True
airportwx   : True
prism_ppt   : False #True
scale       : 0.035

AnnualPrism: 
  var: APRI
  path: 'I:\\urbphen\\AnnualPrism\\us_ppt'

#accumulate:
#  - var  : PRCP
#    times : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
#  - var  : PRCPS
#    times : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#r: 
#  - I:\\urbphen\\Gregs_Scripts_NLCDpatch\\main.R

nlcdcol: I:\\urbphen\\NLCD2006\\nlcdinfo.csv
excludevars:
  - xcoord
  - ycoord
  - tcoord
  - FAVINC0
  - BLTBEF80
  - BLTAFT80
  - NLCD