abbrev  : lax
name    : Los Angeles
gdb     : I:\\urbphen\\newlax\\lax.gdb
outpath : I:\\urbphen\\netcdf\\lax
yaml    : I:\\urbphen\\netcdf\\lax\\info.yaml
netcdf  : I:\\urbphen\\netcdf\\lax\\data.nc
climate_type: med
climate_rank: 7
rainyearmonth : 07
rainyearday : 01

JoinCensus:
  tractshp : I:\\urbphen\\JoinedCensusTracts\\lax.shp
  extractfields:
    - FAVINC0
    - BLTBEF80
    - BLTAFT80

NLCD_Prep:
  file: I:\\urbphen\\NLCD2001\\save\\lax0
  outfile : I:\\urbphen\\NLCD2001\\lax1
  origvals: [11, 12, 21, 22, 23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]   
  newvals : [10, 10, 21, 21, 23, 23, 30, 40, 40, 40, 50, 50, 81, 82, 90, 90]
  thresh : 0.70

landcover:
  file: I:\\urbphen\\NLCD2001\\lax1
  name : NLCD
  dtype: i1
  units: land cover category
  description: Land cover aggregated from NLCD 2001

