
abbrev  : lbb
name    : Lubbock
gdb     : I:\\urbphen\\ws_done\\datasets\\lbb.gdb
outpath : I:\\urbphen\\netcdf\\lbb
yaml    : I:\\urbphen\\netcdf\\lbb\\info.yaml
netcdf  : I:\\urbphen\\netcdf\\lbb\\data.nc
climate_type: semiarid
climate_rank: 2
rainyearmonth : 12
rainyearday : 31

JoinCensus:
  tractshp : I:\\urbphen\\JoinedCensusTracts\\lbb.shp
  extractfields:
    - FAVINC0
    - BLTBEF80
    - BLTAFT80

NLCD_Prep:
  file: I:\\urbphen\\NLCD2001\\save\\lbb0
  outfile : I:\\urbphen\\NLCD2001\\lbb1
  origvals: [11, 12, 21, 22, 23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]   
  newvals : [10, 10, 21, 21, 23, 23, 30, 40, 40, 40, 50, 50, 81, 82, 90, 90]
  thresh : 0.70

landcover:
  file: I:\\urbphen\\NLCD2001\\lbb1
  name : NLCD
  dtype: i1
  units: land cover category
  description: Land cover aggregated from NLCD 2001

